CourseNest MVC/Controllers/AvailableSeatsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CourseNest.Controllers
{
    [Authorize(Roles=nameof(Roles.Admin))]
    public class AvailableSeatsController : Controller
    {
        private readonly ISeatsRepository _seatsRepo;

        public AvailableSeatsController(ISeatsRepository seatsRepo)
        {
            _seatsRepo = seatsRepo;
        }

        public async Task<IActionResult> Index(string sTerm="")
        {
            var seatss=await _seatsRepo.GetSeatss(sTerm);
            return View(seatss);
        }

        public async Task<IActionResult> ManangeSeats(int courseId)
        {
            var existingSeats = await _seatsRepo.GetAvailableSteatsByCourseId(courseId);
            var seats = new SeatsDTO
            {
                CourseId= courseId,
                SeatCount = existingSeats != null
            ? existingSeats.SeatCount : 0
            };
            return View(seats);
        }

        [HttpPost]
        public async Task<IActionResult> ManangeSeats(SeatsDTO seats)
        {
            if (!ModelState.IsValid)
                return View(seats);
            try
            {
                await _seatsRepo.ManageSeats(seats);
                TempData["successMessage"] = "AvailableSeats is updated successfully.";
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = "Something went wrong!!";
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CourseNest MVC/Views/AvailableSeats/Index.cshtml
@model IEnumerable<SeatsDisplayModel>
@{
    Layout = "_AdminLayout";
}
<h2>Seatss</h2>

<form asp-action="Index" method="get" class="my-2 d-flex gap-2">
    <input type="text" name="sTerm" class="form-control w-25" placeholder="Search by course" />
    <button type="submit" class="btn btn-primary">Find</button>
    <a asp-action="Index" asp-controller="AvailableSeats" class="btn btn-primary">Clear</a>
</form>

<table class="table table-benrollmented">
  <tr>
    <th>Course</th>
    <th>AvailableSeats</th>
    <th>Actions</th>
  </tr>
  @foreach(var item in Model)
  {
    <tr>
      <td>@item.CourseName</td>
      <td>@item.SeatCount</td>
      <td>
         <a asp-action="ManangeSeats" asp-controller="AvailableSeats" asp-route-courseId="@item.CourseId" class="btn btn-info"> Update AvailableSeats</a>
      </td>
    </tr>
  }
</table>

CourseNest MVC/Views/AvailableSeats/ManangeSeats.cshtml
@model SeatsDTO
@{
    Layout = "_AdminLayout";
}

<div style="width:50%">
<h2> Manage AvailableSeats </h2>
<a asp-action="Index" asp-controller="AvailableSeats" class="btn btn-primary">Back</a>
<form asp-action="ManangeSeats">
   <input type="hidden" asp-for="CourseId" />

   <div class="my-2">
      <label>SeatCount</label>
      <input type="number" class="form-control" asp-for="SeatCount" />
      <span asp-validation-for="SeatCount" class="text-danger"></span>
   </div>

   <div class="my-2">
      <button type="submit" class="btn btn-info">Update</button>
   </div>
</form>
</div>